# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('submitted', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
