# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('name', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('submitted', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('success', 'success'), ('failed', 'failed')], default='started', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('success', 'success'), ('failed', 'failed')], default='started', max_length=255)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_chunk', to='api.Database')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_chunk', to='api.Job')),
            ],
        ),
    ]
