# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('name', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JobChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('success', 'success'), ('failed', 'failed')], default='started', max_length=255)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_chunk', to='api.Database')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('success', 'success'), ('failed', 'failed')], default='started', max_length=255),
        ),
        migrations.AddField(
            model_name='jobchunk',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_chunk', to='api.Job'),
        ),
    ]
