---
- hosts: load_balancer
  remote_user: cloud-user
  become: yes
  become_user: root
  gather_facts: True
  vars:
    main_ip: "{{ main_ip }}"
    fallback_ip: "{{ fallback_ip }}"
  roles:
    - role: ansible-role-nginx
      nginx_sites:
        upstream:
          template: upstream.conf.j2
      nginx_backend_ip: "{{ main_ip }}"
      nginx_fallback_backend_ip: "{{ fallback_ip }}"
      nginx_backend_port: "8002"
