- name: Download sequence database
  hosts: producer
  become: true
  gather_facts: no
  user: centos

  tasks:
    - name: Download compressed archive from RNAcentral FTP
      get_url:
        url: http://ftp.ebi.ac.uk/pub/databases/RNAcentral/current_release/sequences/.internal/sequences-database.fa.tar.gz
        dest: /nfs/sequence-database.fa.tar.gz

    - name: Uncompress the archive
      shell: tar -xf sequence-database.fa.tar.gz
      args:
        chdir: /nfs
        creates: /nfs/zwd.fasta
