# Playbook to unmount nfs server directory on clients.
# It is recommended to do this before shutting down VMs on GCP to avoid errors.
- name: Unmount nfs
  vars:
    ansible_ssh_private_key_file: "../gcp/gcp_rsa"
    nfs_mount_path: "/nfs"
  hosts: producer:consumers
  become: true
  gather_facts: no
  user: centos

  tasks:
    - name: Unmount nfs server directory on clients
      mount:
        path: "{{ nfs_mount_path }}"
        state: unmounted