---
- hosts: producer
  gather_facts: Yes
  remote_user: centos
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "../terraform/sequence_search_rsa"
    # ansible_ssh_private_key_file: "../gcp/gcp_rsa"
  roles:
    - {role: 'bastion-private-key', tags: 'bastion'}
    - {role: 'producer', tags: 'producer'}
    - ssh
    - iptables
    - swap