CREATE USER burkov WITH ENCRYPTED PASSWORD 'example';
CREATE DATABASE producer;
GRANT ALL PRIVILEGES ON DATABASE producer TO burkov;
ALTER ROLE burkov CREATEDB;
CREATE DATABASE test_producer;
GRANT ALL PRIVILEGES ON DATABASE test_producer TO burkov;