CREATE USER apetrov WITH ENCRYPTED PASSWORD 'example';
CREATE DATABASE producer;
GRANT ALL PRIVILEGES ON DATABASE producer TO apetrov;
ALTER ROLE apetrov CREATEDB;
CREATE DATABASE test_producer;
GRANT ALL PRIVILEGES ON DATABASE test_producer TO apetrov;
